# Generated by Django 6.0.7 on 2026-07-09 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_title', models.CharField(help_text='e.g. Bachelor in Computer Science', max_length=200)),
                ('institution', models.CharField(blank=True, help_text='e.g. UMT', max_length=200, null=True)),
                ('duration', models.CharField(help_text='e.g. 2023 - 2027 or In Progress', max_length=100)),
                ('score', models.CharField(blank=True, help_text='e.g. 1096/1100 or CGPA 3.29', max_length=100, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first')),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Education Entries',
                'ordering': ['order', '-id'],
            },
        ),
    ]
