# Generated by Django 6.0.7 on 2026-07-09 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('job_title', models.CharField(help_text='e.g. Video - Photographer and Editor', max_length=200)),
                ('profile_picture', models.ImageField(upload_to='profile/')),
                ('description', models.TextField(help_text='Objective / About Me paragraph')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_primary', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_secondary', models.CharField(blank=True, max_length=20, null=True)),
                ('facebook', models.CharField(blank=True, help_text='Facebook username/handle', max_length=150, null=True)),
                ('instagram', models.CharField(blank=True, help_text='Instagram username/handle', max_length=150, null=True)),
                ('work_drive_link', models.URLField(blank=True, help_text='Link to portfolio work / drive folder', null=True)),
            ],
            options={
                'verbose_name': 'Bio',
                'verbose_name_plural': 'Bio',
            },
        ),
    ]
