# Generated by Django 6.0.7 on 2026-07-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='github',
            field=models.CharField(blank=True, help_text='GitHub username', max_length=150, null=True),
        ),
    ]
