# Generated by Django 6.0.7 on 2026-07-09 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Short heading, e.g. 'Self-taught Video Editing'", max_length=200)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Experience',
                'verbose_name_plural': 'Work Experience',
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('video', 'Video / Reel'), ('film', 'Short Film'), ('web', 'Web Development'), ('game', 'Game Development'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('link', models.URLField(blank=True, help_text='Link to the project, video, or repo', null=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['order', '-id'],
            },
        ),
    ]
