# Generated by Django 6.0.7 on 2026-07-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('creative', 'Creative'), ('technical', 'Technical')], default='creative', max_length=20),
        ),
    ]
